import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import './globals.css';
import { CurrencyProvider } from '@/providers/CurrencyProvider';

const publicSans = Public_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'finance-app',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.className} antialiased bg-beige-100 text-grey-900`}
      >
        <CurrencyProvider>
          {children}
        </CurrencyProvider>
      </body>
    </html>
  );
}
