import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import './globals.css';
import { CurrencyProvider } from '@/providers/CurrencyProvider';
import ConvexClientProvider from "./ConvexClientProvider";

const publicSans = Public_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'finance-app',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${publicSans.className} antialiased bg-beige-100 text-grey-900`}
      >
        <ConvexClientProvider>
          <CurrencyProvider>
            {children}
          </CurrencyProvider>
        </ConvexClientProvider>

      </body>
    </html>
  );
}